appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: EjG9ATLjzTCmFfXklm+0AV360z25DERlGOVUUFNxjZC3c9lPWFsZqPbAgTezRE0t3Dsc0mX1hSgwSuN96u+Vog8fxxQKRSvKoEh9YqCTHysrHVWqDHfeqv7SHOiDpF1rcwhJJriygNd2zhX68/xLOtWiDhrS7x0W6pwwyyxNgF9b2bC2oI+dOz7DCJUcsq1x9bO7wR1fHfCYQwK10Z88U5Jj7BPcbZDiUHvh1/IBNvPaRBzSFUO4qsT1fNKut+us9YQRAcD94JK+05LNeFXMs9oMFvtbDah+CQiD3kHPmQ4WF089lZigA7QN7EUpFPHMxnh79gu3cj41wXEZfSKHznFznS9R/FPqAdgrAJiA0rp62sTE3B5bL89MMYkXizDJCwjegt+y5htx8b1//pYrn/Iwvw3W37/bdxYlqx7LO0m/OzWasXyby98+I0K15R+Cj4jmz6TiBkIYzu9SyQ1L/C9MnGbtIm+YVdNrp4+uAO5h13BPd3woVc2Rq7bWg+Qwu0mVQfTIBYfWEE6PkYvI69qSq108vtpSTaR/QM5pFRL8N7D6vzCG/FxJa9voQtSb71jb2YUhcysdBEHn5Xqa+BXzcjXimWXQ+BDpbyeAczL8fPFAe1MbnWpztQ+Om2Yg76OQ2R5EM2dSF78jQnhYOpooo2vCvg0to0/G8F2ig6s=}
bot:
  automerge: true
